---
title: "Thesis EDA"
author: "Harrison DiStefano"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(dplyr)
library(fable)
library(fabletools)
library(feasts)
library(ggplot2)
library(tidyr)
library(tseries)
library(tsibble)
library(urca)
```



```{r load data}
housing <- read.csv('data/processed.csv')
head(housing)
```


```{r data cleaning}
housing$DATE <- as.Date(housing$DATE, format = "%Y-%m-%d")
housing_ts <- housing %>%
                select(-X) %>%  # Remove integer index
                mutate(YearMonth = yearmonth(as.character(DATE))) %>%
                as_tsibble(index = YearMonth)
head(housing_ts)
```


```{r chart1}
variables <- colnames(housing_ts)
variables <- variables[-1]  # Remove date column

housing_ts %>%
  pivot_longer(c('MSPUS', 'MSACSR', 'S.P.Comp.', 'CPI', 'Long.Interest.Rate.GS10'),
               names_to = "var", values_to = "value") %>%
  ggplot(aes(x = DATE, y = value, group = 1)) +
  geom_line() +
  facet_grid(vars(var), scales = "free_y") +
  scale_x_date(date_breaks = "5 year", date_labels = "%Y") +
  labs(title = "",
       y = "")

ggsave(filename = "major_variables.png",
       path = "figures",
       plot = last_plot(),
       device = "png")
```

```{r differencing}
# Make housing prices stationary
housing_ts$pctChangeMSPUS <- c(0, diff(log(housing$MSPUS)))  # diff log calculates symmetric % change
                                                          # Add 0 add beginning to match row length

housing_ts %>%
  ggplot(aes(x = DATE, y = pctChangeMSPUS)) +
  geom_line()
```

```{r stationarity test}
# Ljung-Box test for independence - stationarity
Box.test(housing_ts$pctChangeMSPUS, lag=25, type="Ljung-Box")

# Augmented Dickey-Fuller (ADF) t-statistic test for unit root
adf.test(housing_ts$pctChangeMSPUS)

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity
kpss.test(housing_ts$pctChangeMSPUS, null="Trend")
```

```{r ARIMA Regression}
fit <- housing_ts %>%
  fabletools::model(fable::ARIMA(pctChangeMSPUS ~ MSACSR))

report(fit)
```

```{r ARIMA Lagged Predictors}
fit <- housing_ts %>%
  model(
    lag0 = ARIMA(pctChangeMSPUS ~ pdq(d = 0) + MSACSR),
    lag1 = ARIMA(pctChangeMSPUS ~ pdq(d = 0) + MSACSR + lag(MSACSR)),
    lag2 = ARIMA(pctChangeMSPUS ~ pdq(d = 0) + MSACSR + lag(MSACSR) +
                 lag(MSACSR, 2)),
    lag3 = ARIMA(pctChangeMSPUS ~ pdq(d = 0) + MSACSR + lag(MSACSR) +
                 lag(MSACSR, 2) + lag(MSACSR, 3))
  )

glance(fit)
```

